// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN4tR1lqfALU01fJ64V41gu2KwppNzhCs',
    appId: '1:597918726130:web:aca44fd0f1281bf7e69d6b',
    messagingSenderId: '597918726130',
    projectId: 'area-skills',
    authDomain: 'area-skills.firebaseapp.com',
    storageBucket: 'area-skills.firebasestorage.app',
    measurementId: 'G-W5FJ1X8SH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATR1BW5jmxw0i_aHfUxWdVJHQd_YWu3wE',
    appId: '1:597918726130:android:1a9d01409ff070d2e69d6b',
    messagingSenderId: '597918726130',
    projectId: 'area-skills',
    storageBucket: 'area-skills.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzWP2iJReIBKMeZhhjTY1Y89WjOoVQPyY',
    appId: '1:597918726130:ios:521a8ae386a88003e69d6b',
    messagingSenderId: '597918726130',
    projectId: 'area-skills',
    storageBucket: 'area-skills.firebasestorage.app',
    iosBundleId: 'com.example.plz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzWP2iJReIBKMeZhhjTY1Y89WjOoVQPyY',
    appId: '1:597918726130:ios:521a8ae386a88003e69d6b',
    messagingSenderId: '597918726130',
    projectId: 'area-skills',
    storageBucket: 'area-skills.firebasestorage.app',
    iosBundleId: 'com.example.plz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN4tR1lqfALU01fJ64V41gu2KwppNzhCs',
    appId: '1:597918726130:web:7094766eb62beabfe69d6b',
    messagingSenderId: '597918726130',
    projectId: 'area-skills',
    authDomain: 'area-skills.firebaseapp.com',
    storageBucket: 'area-skills.firebasestorage.app',
    measurementId: 'G-L8Y06ZE2WP',
  );
}
